# Site settings
title: Elkhan Dadashov's blog
email: 
description: "Knowledge Share"
baseurl: ""
url: "http://elkhand.github.io"
twitter_username: elkhandad
github_username:  elkhand
linkedin_username: elkhandadashov

timezone: "America/Los_Angeles"

# Build settings
markdown: kramdown
permalink: pretty

paginate: 5
paginate_path: "/blog/post:num/"

gems: 
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist

gems: [jekyll-paginate,jekyll-sitemap,jekyll-gist]

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge